---
# Defines tasks to install and configure Logwatch

- name: Gather OS specific varibles
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - logwatch

- include: "{{ ansible_os_family }}/install.yml"
  static: no
  tags:
    - logwatch

- name: Write configuration templates
  template: >
    src=logwatch-conf.j2
    dest="{{ logwatch_config_dir }}/logwatch.conf"
    mode=0644 owner=root group=root
    backup=yes
  tags:
    - logwatch

- name: Create cache directory
  file: >
    path="{{ logwatch_tmp_dir }}"
    state=directory
    mode=0755 owner=root group=root
  tags:
    - logwatch

- name: Create script to parse duply log files
  template: src=duply-service.pl.j2 dest=/usr/share/logwatch/scripts/services/duply owner=root group=root mode="u=rwx,g=r,o=r"
  tags:
    - logwatch

- name: Create logfile definition for duply log files
  template: src=duply-logfile.j2 dest=/etc/logwatch/conf/logfiles/duply.conf owner=root group=root mode="u=rw,g=r,o=r"
  tags:
    - logwatch

- name: Create service configuration for duply log files
  template: src=duply-service.conf.j2 dest=/etc/logwatch/conf/services/duply.conf owner=root group=root mode="u=rw,g=r,o=r"
  tags:
    - logwatch
